# Generated by Django 4.2.29 on 2026-03-11 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('course', 'Курс'), ('webinar', 'Вебінар'), ('membership', 'Членство')], max_length=20, verbose_name='Тип')),
                ('item_id', models.PositiveIntegerField(verbose_name='ID товару')),
                ('item_title', models.CharField(blank=True, max_length=255, verbose_name='Назва товару')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума')),
                ('currency', models.CharField(default='UAH', max_length=3, verbose_name='Валюта')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('paid', 'Оплачено'), ('failed', 'Помилка'), ('refunded', 'Повернення')], default='pending', max_length=20, verbose_name='Статус')),
                ('stripe_session_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Stripe Session ID')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, verbose_name='Stripe Payment Intent ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-created_at'],
            },
        ),
    ]
