# Generated by Django 6.0.1 on 2026-04-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Ім'я та прізвище")),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(blank=True, verbose_name='Повідомлення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обробленої')),
            ],
            options={
                'verbose_name': 'Заявка на консультацію',
                'verbose_name_plural': 'Заявки на консультацію',
                'ordering': ['-created_at'],
            },
        ),
    ]
