# Generated by Django 4.2.29 on 2026-04-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_newslettersubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
            ],
            options={
                'verbose_name': 'Контактні дані сайту',
                'verbose_name_plural': 'Контактні дані сайту',
            },
        ),
    ]
