# Generated by Django 6.0.1 on 2026-02-28 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна/міс')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('features', models.JSONField(default=list, verbose_name='Переваги')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярний')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Тарифний план',
                'verbose_name_plural': 'Тарифні плани',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Активне'), ('expired', 'Закінчилось'), ('cancelled', 'Скасовано')], default='active', max_length=20)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.membershipplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Членство користувача',
                'verbose_name_plural': 'Членства користувачів',
            },
        ),
    ]
