# Generated by Django 6.0.1 on 2026-04-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_membershipplan_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipplan',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR (€) - Euro'), ('UAH', 'UAH (₴) - Ukrainian Hryvnia'), ('USD', 'USD ($) - US Dollar'), ('GBP', 'GBP (£) - British Pound'), ('CHF', 'CHF (Fr) - Swiss Franc'), ('PLN', 'PLN (zł) - Polish Zloty')], default='EUR', max_length=3, verbose_name='Валюта'),
        ),
    ]
