# Generated by Django 6.0.1 on 2026-02-28 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(verbose_name='Опис')),
                ('cover', models.ImageField(blank=True, upload_to='courses/covers/', verbose_name='Обкладинка')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('duration_hours', models.PositiveIntegerField(default=0, verbose_name='Тривалість (год)')),
                ('level', models.CharField(choices=[('beginner', 'Початківець'), ('intermediate', 'Середній'), ('advanced', 'Просунутий')], default='beginner', max_length=20, verbose_name='Рівень')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярний')),
                ('requires_membership', models.BooleanField(default=False, verbose_name='Тільки для членів')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.category')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курси',
                'ordering': ['-created_at'],
            },
        ),
    ]
