# Generated by Django 4.2.29 on 2026-03-11 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='bunny_library_id',
            field=models.CharField(blank=True, help_text='ID бібліотеки Bunny.net Stream (якщо відрізняється від глобального)', max_length=100, verbose_name='Bunny Library ID'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_courses', to=settings.AUTH_USER_MODEL, verbose_name='Лектор'),
        ),
        migrations.AddField(
            model_name='course',
            name='what_you_learn',
            field=models.JSONField(blank=True, default=list, help_text='Список пунктів, напр. ["Основи нутріціології", "Розрахунок раціонів"]', verbose_name='Чому навчитесь'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('bunny_video_id', models.CharField(blank=True, help_text='GUID відео в Bunny.net Stream', max_length=100, verbose_name='Bunny Video ID')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='Тривалість (сек)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_preview', models.BooleanField(default=False, help_text='Дозволити перегляд без покупки курсу', verbose_name='Безкоштовний перегляд')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['order'],
                'unique_together': {('course', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата запису')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='Курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Запис на курс',
                'verbose_name_plural': 'Записи на курси',
                'unique_together': {('user', 'course')},
            },
        ),
    ]
