# Generated by Django 6.0.1 on 2026-04-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_new_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='promo_bunny_video_id',
            field=models.CharField(blank=True, help_text='GUID промо-відео курсу в Bunny.net Stream', max_length=100, verbose_name='Промо-відео (Bunny Video ID)'),
        ),
    ]
