# Generated by Django 6.0.1 on 2026-04-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_promo_bunny_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='currency',
            field=models.CharField(default='EUR', max_length=3, verbose_name='Валюта'),
        ),
    ]
