# Generated by Django 6.0.1 on 2026-02-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(verbose_name='Опис')),
                ('cover', models.ImageField(blank=True, upload_to='webinars/covers/', verbose_name='Обкладинка')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата проведення')),
                ('duration_min', models.PositiveIntegerField(default=60, verbose_name='Тривалість (хв)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('requires_membership', models.BooleanField(default=False, verbose_name='Тільки для членів')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Вебінар',
                'verbose_name_plural': 'Вебінари',
                'ordering': ['-date'],
            },
        ),
    ]
