# Generated by Django 4.2.29 on 2026-03-11 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webinars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='bunny_library_id',
            field=models.CharField(blank=True, help_text='ID бібліотеки Bunny.net Stream', max_length=100, verbose_name='Bunny Library ID'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='bunny_video_id',
            field=models.CharField(blank=True, help_text='GUID відео-запису вебінару в Bunny.net Stream', max_length=100, verbose_name='Bunny Video ID'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='Безкоштовний'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webinars_as_speaker', to=settings.AUTH_USER_MODEL, verbose_name='Спікер'),
        ),
        migrations.CreateModel(
            name='WebinarRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата реєстрації')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webinar_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='webinars.webinar', verbose_name='Вебінар')),
            ],
            options={
                'verbose_name': 'Реєстрація на вебінар',
                'verbose_name_plural': 'Реєстрації на вебінари',
                'unique_together': {('user', 'webinar')},
            },
        ),
    ]
