# Generated by Django 6.0.1 on 2026-04-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0002_webinar_bunny_library_id_webinar_bunny_video_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='audience',
            field=models.CharField(choices=[('owners', 'Для власників'), ('experts', 'Для експертів')], default='owners', max_length=20, verbose_name='Тематика (аудиторія)'),
        ),
    ]
