# Generated by Django 6.0.1 on 2026-04-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0005_seed_initial_webinars'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='currency',
            field=models.CharField(default='EUR', max_length=3, verbose_name='Валюта'),
        ),
    ]
