# Generated by Django 6.0.1 on 2026-04-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0006_webinar_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='materials_access_note',
            field=models.TextField(blank=True, default='', verbose_name='Умови доступу до матеріалів'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='what_you_learn',
            field=models.JSONField(blank=True, default=list, help_text='Список пунктів, напр. ["Основи нутріціології", "Розрахунок раціонів"]', verbose_name='Чому навчитесь'),
        ),
    ]
