# Generated by Django 6.0.1 on 2026-04-23 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0008_populate_webinar_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebinarInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ПІБ')),
                ('role', models.CharField(blank=True, max_length=255, verbose_name='Роль/посада')),
                ('bio', models.TextField(blank=True, verbose_name='Біографія')),
                ('photo', models.ImageField(blank=True, upload_to='webinar_instructors/', verbose_name='Фото')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='webinars.webinar', verbose_name='Вебінар')),
            ],
            options={
                'verbose_name': 'Спікер вебінару',
                'verbose_name_plural': 'Спікери вебінарів',
                'ordering': ['order'],
            },
        ),
    ]
